
package com.verisign.dnsa.api.wsdl._2;

import javax.xml.ws.WebFault;
import com.verisign.dnsa.api.schema._1.BaseDnsaResType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "dnsaWSRes", targetNamespace = "urn:com:verisign:dnsa:api:schema:1")
public class DnsaGenErrorRes
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BaseDnsaResType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public DnsaGenErrorRes(String message, BaseDnsaResType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public DnsaGenErrorRes(String message, BaseDnsaResType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.verisign.dnsa.api.schema._1.BaseDnsaResType
     */
    public BaseDnsaResType getFaultInfo() {
        return faultInfo;
    }

}
